name: evea
version: 1

libraries:
- name: "django"
  version: "1.4"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_path: favicon.ico

- url: /robots.txt
  static_path: robots.txt
